config/routes.rb
Rails.application.routes.draw do

  # namespace :admin do
  # end
  # # mount Fae below your admin namespec
  # mount Fae::Engine => '/admin'


  namespace :admin do
    resources :bookings
    resources :tours
    resources :wineries
    resources :tour_dairies
    resources :tour_dairies
    resources :wine_reviews
    resources :users
    resources :wines
    resources :foods
  end
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  include Fae::BaseModelConcern
  def fae_display_field
    
  end

  belongs_to :tour
  belongs_to :user
end

app/models/concerns/fae/authorization_concern.rb
module Fae
  module AuthorizationConcern
    extend ActiveSupport::Concern
    module ClassMethods

      # Use the access_map to define any controllers that need any special authorization
      # Fae comes with three default roles:
      # - super admin: CRUD all objects, INCLUDING users and root settings
      # - admin: CRUD all objects, INCLUDING users and EXCLUDING root settings
      # - users: CRUD all objects, EXCLUDING users and root settings

      # each item should have a string key of the plural controller name and
      # an array of role names for the value
      # use "content_blocks/#{page_name}" for content blocks

      # example:
      # {
      #  'people' => ['super admin', 'admin'],
      #  'content_blocks/about_us' => ['super admin']
      # }
      def access_map
        {}
      end

    end
  end
end

app/models/concerns/fae/navigation_concern.rb
module Fae
  module NavigationConcern
    extend ActiveSupport::Concern

    # define the navigation structure in this file
    # example structure:
    #
    # def structure
    #   [
    #     item('Top Nav Item 1', subitems: [
    #       item('Top Nav Dropdown Item 1', class: 'custom-class', path: some_named_route_path),
    #       item('Top Nav Dropdown Item 2', subitems: [
    #         item('Side Nav Item 1', subitems: [
    #           item('Side Nav Nested Item', path: some_named_route_path)
    #         ]),
    #         item('Side Nav Item 1', path: some_named_route_path)
    #       ]),
    #     ]),
    #     item('Pages', subitems: [
    #       item('Home', path: fae.edit_content_block_path('home')),
    #       item('About Us', path: fae.edit_content_block_path('about_us'))
    #     ])
    #   ]
    # end

    def structure
      [
        # scaffold inject marker
      ]
    end

  end
end

app/models/food.rb
class Food < ApplicationRecord
  include Fae::BaseModelConcern
  has_fae_image :food_image

  def fae_display_field
    name
  end

end

app/models/tour.rb
class Tour < ApplicationRecord
  include Fae::BaseModelConcern
  has_fae_image :tour_image

  def fae_display_field
    
  end

  belongs_to :winery
end

app/models/tour_dairy.rb
class TourDairy < ApplicationRecord
  include Fae::BaseModelConcern

  include Fae::BaseModelConcern
  has_fae_image :tour_image

  has_fae_file :video

  def fae_display_field

  end

  belongs_to :winereview
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  include Fae::BaseModelConcern
  def fae_display_field
    name
  end

end

app/models/wine.rb
class Wine < ApplicationRecord
  include Fae::BaseModelConcern
  has_fae_image :wine_image

  def fae_display_field
    name
  end

  belongs_to :food
end

app/models/wine_review.rb
class WineReview < ApplicationRecord
  include Fae::BaseModelConcern
  def fae_display_field
    
  end

  belongs_to :wine
end

app/models/winery.rb
class Winery < ApplicationRecord
  include Fae::BaseModelConcern
  has_fae_image :winery_image

  def fae_display_field
    name
  end

  belongs_to :wine
end

app/controllers/admin/bookings_controller.rb
module Admin
  class BookingsController < Fae::BaseController

  end
end

app/controllers/admin/foods_controller.rb
module Admin
  class FoodsController < Fae::BaseController

    private

    def build_assets
      @item.build_food_image if @item.food_image.blank?
    end

  end
end

app/controllers/admin/tour_dairies_controller.rb
module Admin
  class TourDairiesController < Fae::BaseController

    private

    def build_assets
      @item.build_video if @item.video.blank?
      @item.build_tour_image if @item.tour_image.blank?
    end

  end
end

app/controllers/admin/tours_controller.rb
module Admin
  class ToursController < Fae::BaseController

    private

    def build_assets
      @item.build_tour_image if @item.tour_image.blank?
    end

  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Fae::BaseController

  end
end

app/controllers/admin/wine_reviews_controller.rb
module Admin
  class WineReviewsController < Fae::BaseController

  end

  # def self.for_fae_index
  # order(:WineReviews)
  # end
end

app/controllers/admin/wineries_controller.rb
module Admin
  class WineriesController < Fae::BaseController

    private

    def build_assets
      @item.build_winery_image if @item.winery_image.blank?
    end

  end
end

app/controllers/admin/wines_controller.rb
module Admin
  class WinesController < Fae::BaseController

    private

    def build_assets
      @item.build_wine_image if @item.wine_image.blank?
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/bookings/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :price

    = fae_association f, :tour
    = fae_association f, :user

app/views/admin/bookings/edit.html.slim
== render 'form'

app/views/admin/bookings/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Name
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_booking_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/bookings/new.html.slim
== render 'form'

app/views/admin/foods/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :name


    = fae_image_form f, :food_image

app/views/admin/foods/edit.html.slim
== render 'form'

app/views/admin/foods/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Name
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_food_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/foods/new.html.slim
== render 'form'

app/views/admin/tour_dairies/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :qrcode_image
    = fae_input f, :content

    = fae_association f, :wine_review
    = fae_association f, :user

    = fae_file_form f, :video
    = fae_image_form f, :tour_image

app/views/admin/tour_dairies/edit.html.slim
== render 'form'

app/views/admin/tour_dairies/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Name
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_tour_dairy_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/tour_dairies/new.html.slim
== render 'form'

app/views/admin/tours/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :date
    = fae_input f, :length
    = fae_input f, :pax
    = fae_input f, :price
    = fae_input f, :content

    = fae_association f, :winery

    = fae_image_form f, :tour_image

app/views/admin/tours/edit.html.slim
== render 'form'

app/views/admin/tours/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Name
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_tour_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/tours/new.html.slim
== render 'form'

app/views/admin/users/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :name
    = fae_input f, :avatar_url
    = fae_input f, :wechat_id

    / = fae_association f, :wechat_id

app/views/admin/users/edit.html.slim
== render 'form'

app/views/admin/users/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Name
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_user_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/users/new.html.slim
== render 'form'

app/views/admin/wine_reviews/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :content
    = fae_input f, :rating

    = fae_association f, :wine

app/views/admin/wine_reviews/edit.html.slim
== render 'form'

app/views/admin/wine_reviews/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Name
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_wine_review_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/wine_reviews/new.html.slim
== render 'form'

app/views/admin/wineries/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :name
    / = fae_input f, :country
    = fae_input f, :content
    = fae_input f, :location

    = fae_association f, :wine

    = fae_image_form f, :winery_image

app/views/admin/wineries/edit.html.slim
== render 'form'

app/views/admin/wineries/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Name
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_winery_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/wineries/new.html.slim
== render 'form'

app/views/admin/wines/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :name
    = fae_input f, :year
    = fae_input f, :price

    = fae_association f, :food

    = fae_image_form f, :wine_image

app/views/admin/wines/edit.html.slim
== render 'form'

app/views/admin/wines/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Name
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_wine_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/wines/new.html.slim
== render 'form'